/*
Copyright 2021 The Optum Authors
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/optum/kafka-topic-channel/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// KafkaTopicChannels returns a KafkaTopicChannelInformer.
	KafkaTopicChannels() KafkaTopicChannelInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// KafkaTopicChannels returns a KafkaTopicChannelInformer.
func (v *version) KafkaTopicChannels() KafkaTopicChannelInformer {
	return &kafkaTopicChannelInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
