/*
Copyright 2021 The Optum Authors
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	messagingv1alpha1 "github.com/optum/kafka-topic-channel/pkg/apis/messaging/v1alpha1"
	versioned "github.com/optum/kafka-topic-channel/pkg/client/clientset/versioned"
	internalinterfaces "github.com/optum/kafka-topic-channel/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/optum/kafka-topic-channel/pkg/client/listers/messaging/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KafkaTopicChannelInformer provides access to a shared informer and lister for
// KafkaTopicChannels.
type KafkaTopicChannelInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KafkaTopicChannelLister
}

type kafkaTopicChannelInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKafkaTopicChannelInformer constructs a new informer for KafkaTopicChannel type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKafkaTopicChannelInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKafkaTopicChannelInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKafkaTopicChannelInformer constructs a new informer for KafkaTopicChannel type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKafkaTopicChannelInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MessagingV1alpha1().KafkaTopicChannels(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MessagingV1alpha1().KafkaTopicChannels(namespace).Watch(context.TODO(), options)
			},
		},
		&messagingv1alpha1.KafkaTopicChannel{},
		resyncPeriod,
		indexers,
	)
}

func (f *kafkaTopicChannelInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKafkaTopicChannelInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kafkaTopicChannelInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&messagingv1alpha1.KafkaTopicChannel{}, f.defaultInformer)
}

func (f *kafkaTopicChannelInformer) Lister() v1alpha1.KafkaTopicChannelLister {
	return v1alpha1.NewKafkaTopicChannelLister(f.Informer().GetIndexer())
}
