/*
Copyright 2021 The Optum Authors
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/optum/kafka-topic-channel/pkg/apis/messaging/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKafkaTopicChannels implements KafkaTopicChannelInterface
type FakeKafkaTopicChannels struct {
	Fake *FakeMessagingV1alpha1
	ns   string
}

var kafkatopicchannelsResource = schema.GroupVersionResource{Group: "messaging.optum.dev", Version: "v1alpha1", Resource: "kafkatopicchannels"}

var kafkatopicchannelsKind = schema.GroupVersionKind{Group: "messaging.optum.dev", Version: "v1alpha1", Kind: "KafkaTopicChannel"}

// Get takes name of the kafkaTopicChannel, and returns the corresponding kafkaTopicChannel object, and an error if there is any.
func (c *FakeKafkaTopicChannels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KafkaTopicChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kafkatopicchannelsResource, c.ns, name), &v1alpha1.KafkaTopicChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaTopicChannel), err
}

// List takes label and field selectors, and returns the list of KafkaTopicChannels that match those selectors.
func (c *FakeKafkaTopicChannels) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KafkaTopicChannelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kafkatopicchannelsResource, kafkatopicchannelsKind, c.ns, opts), &v1alpha1.KafkaTopicChannelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KafkaTopicChannelList{ListMeta: obj.(*v1alpha1.KafkaTopicChannelList).ListMeta}
	for _, item := range obj.(*v1alpha1.KafkaTopicChannelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kafkaTopicChannels.
func (c *FakeKafkaTopicChannels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kafkatopicchannelsResource, c.ns, opts))

}

// Create takes the representation of a kafkaTopicChannel and creates it.  Returns the server's representation of the kafkaTopicChannel, and an error, if there is any.
func (c *FakeKafkaTopicChannels) Create(ctx context.Context, kafkaTopicChannel *v1alpha1.KafkaTopicChannel, opts v1.CreateOptions) (result *v1alpha1.KafkaTopicChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kafkatopicchannelsResource, c.ns, kafkaTopicChannel), &v1alpha1.KafkaTopicChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaTopicChannel), err
}

// Update takes the representation of a kafkaTopicChannel and updates it. Returns the server's representation of the kafkaTopicChannel, and an error, if there is any.
func (c *FakeKafkaTopicChannels) Update(ctx context.Context, kafkaTopicChannel *v1alpha1.KafkaTopicChannel, opts v1.UpdateOptions) (result *v1alpha1.KafkaTopicChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kafkatopicchannelsResource, c.ns, kafkaTopicChannel), &v1alpha1.KafkaTopicChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaTopicChannel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKafkaTopicChannels) UpdateStatus(ctx context.Context, kafkaTopicChannel *v1alpha1.KafkaTopicChannel, opts v1.UpdateOptions) (*v1alpha1.KafkaTopicChannel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kafkatopicchannelsResource, "status", c.ns, kafkaTopicChannel), &v1alpha1.KafkaTopicChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaTopicChannel), err
}

// Delete takes name of the kafkaTopicChannel and deletes it. Returns an error if one occurs.
func (c *FakeKafkaTopicChannels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kafkatopicchannelsResource, c.ns, name), &v1alpha1.KafkaTopicChannel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKafkaTopicChannels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kafkatopicchannelsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KafkaTopicChannelList{})
	return err
}

// Patch applies the patch and returns the patched kafkaTopicChannel.
func (c *FakeKafkaTopicChannels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KafkaTopicChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kafkatopicchannelsResource, c.ns, name, pt, data, subresources...), &v1alpha1.KafkaTopicChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaTopicChannel), err
}
