/*
Copyright 2021 The Optum Authors
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/optum/kafka-topic-channel/pkg/client/clientset/versioned/typed/messaging/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMessagingV1alpha1 struct {
	*testing.Fake
}

func (c *FakeMessagingV1alpha1) KafkaTopicChannels(namespace string) v1alpha1.KafkaTopicChannelInterface {
	return &FakeKafkaTopicChannels{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMessagingV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
