/*
Copyright 2021 The Optum Authors
*/

// Code generated by injection-gen. DO NOT EDIT.

package fake

import (
	context "context"

	fake "github.com/optum/kafka-topic-channel/pkg/client/injection/informers/factory/fake"
	kafkatopicchannel "github.com/optum/kafka-topic-channel/pkg/client/injection/informers/messaging/v1alpha1/kafkatopicchannel"
	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
)

var Get = kafkatopicchannel.Get

func init() {
	injection.Fake.RegisterInformer(withInformer)
}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := fake.Get(ctx)
	inf := f.Messaging().V1alpha1().KafkaTopicChannels()
	return context.WithValue(ctx, kafkatopicchannel.Key{}, inf), inf.Informer()
}
