apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cev
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: ghcr.io/itsmurugappan/cev
