apiVersion: sources.knative.dev/v1beta2
kind: PingSource
metadata:
  name: channel-pingsource
spec:
  schedule: "*/1 * * * *"
  contentType: "application/json"
  data: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: ktc-example-broker