apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kt-channel-controller
subjects:
- kind: ServiceAccount
  name: kt-channel-controller
  namespace: knative-eventing
roleRef:
  kind: ClusterRole
  name: kt-channel-controller
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafka-ch-dispatcher
subjects:
- kind: ServiceAccount
  name: kt-channel-dispatcher
  namespace: knative-eventing
roleRef:
  kind: ClusterRole
  name: kafka-ch-dispatcher
  apiGroup: rbac.authorization.k8s.io
