/*
Copyright 2021 The Optum Authors
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// KafkaTopicChannelListerExpansion allows custom methods to be added to
// KafkaTopicChannelLister.
type KafkaTopicChannelListerExpansion interface{}

// KafkaTopicChannelNamespaceListerExpansion allows custom methods to be added to
// KafkaTopicChannelNamespaceLister.
type KafkaTopicChannelNamespaceListerExpansion interface{}
