apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kt-channelable-manipulator
  labels:
    duck.knative.dev/channelable: "true"
# Do not use this role directly. These rules will be added to the "channelable-manipulator" role.
rules:
  - apiGroups:
      - messaging.optum.dev
    resources:
      - kafkatopicchannels
      - kafkatopicchannels/status
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
